name: Hexo Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the hexo branch
  push:
    branches:
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true # Checkout private submodules(themes or something else).

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "feifeifeimoon"
          git config --global user.email "wangyufeimoon@gmail.com"

      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i

      - name: Deploy hexo
      - env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
        run: |
          sed -i "s/gitalk_client_id/${CLIENT_ID}/" _config.next.yml
          sed -i "s/gitalk_client_secret/${CLIENT_SECRET}/" _config.next.yml
          cp special/layout/_layout.swig themes/next/layout/
          hexo deploy
